import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <style jsx>
        {`
         h2{
          font-size: 38px;
         }
          h3{
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnload'>  </Script> */}
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='mySpan dummy'>Hunting Coder</span>
          
        </h1>
<div className={styles.imgwrap}>
<Image src="/code.jpg" className={styles.myImg} width={237} height={158} />
</div>        <p className={styles.description}>
          A blog for hunting coders by a coder
        </p>
        <div>
          <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JS us the language used to design logic for the web</p>
            <p>JS us the language used to design logic for the web</p>
            <p>JS us the language used to design logic for the web</p>
            <p>JS us the language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
